### PR TITLE
Feature/tino

### PR DESCRIPTION
**Pull request by TinoTC**
All search buttons have stat display and should properly display stats for a user found in that console database.

### CODE REVIEW

**Comment by TinoTC** [comment]
The error message displayed if search is empty should return a custom message depending on console type.

**Review by Zoombabyy — APPROVED** [review]

**Comment by TinoTC** [comment]
Added 'add to favorites' button to stat display for all console types.

**Comment by TinoTC** [comment]
All back buttons have functionality.

**Comment by TinoTC** [comment]
Added interactivity to 'add to fav' button.

**Comment by TinoTC** [comment]
Debugging add to fav button!

**Comment by TinoTC** [comment]
'Add to favorites' functionality has been debugged!

**Comment by TinoTC** [comment]
Still must add save functionality to xbox and pc console types"

**Pull request merged**
